### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#426]
Add linting support to the codebase. Can be included into the CI pipeline later when all linting issues are fixed. Also already fixes some linting issues.
EDIT: Has been added to the pipeline and remaining issues were fixed

**Comment by datdamnzotz** [comment]
When trying to save a character.
Description - > Player name or XP, really anything..

```
[qtp827598152-265] INFO io.pedestal.http - {:msg "POST /dnd/5e/characters", :line 78}
[qtp827598152-265] INFO io.pedestal.http.cors - {:msg "cors request processing", :origin "http://localhost:8890", :allowed true, :line 84}
"ERROR" #error {
 :cause ":db.error/not-transaction-data Transaction data element must be a List or Map, got "
 :data {:db/error :db.error/not-transaction-data}
 :via
 [{:type java.util.concurrent.ExecutionException
   :message "java.lang.IllegalArgumentException: :db.error/not-transaction-data Transaction data element must be a List or Map, got "
   :at [datomic.promise$throw_executionexception_if_throwable invokeStatic "promise.clj" 10]}
  {:type datomic.impl.Exceptions$IllegalArgumentExceptionInfo
   :message ":db.error/not-transaction-data Transaction data element must be a List or Map, got "
   :data {:db/error :db.error/not-transaction-data}
   :at [datomic.error$arg invokeStatic "error.clj" 57]}]
 :trace
 [[datomic.error$arg invokeStatic "error.clj" 57]
  [datomic.error$arg invoke "error.clj" 52]
  [datomic.error$arg invokeStatic "error.clj" 55]
  [datomic.error$arg invoke "error.clj" 52]
  [datomic.transaction$inject_all$fn__4990 invoke "transaction.clj" 128]
  [clojure.core.protocols$fn__8144 invokeS[qtp827598152-265] ERROR io.pedestal.http.impl.servlet-interceptor - {:msg "Dev interceptor caught an exception; Forwarding it as the response.", :line 313}tatic "protocols.clj" 168]
  [clojure.core.protocols$fn__8144 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8099$G__8094__8108 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8129 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8129 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8073$G__8068__8086 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$reduce invoke "core.clj" 6810]
  [datomic.transaction$inject_all invokeStatic "transaction.clj" 123]
  [datomic.transaction$inject_all invoke "transaction.clj" 121]
  [datomic.peer.Connection transactAsync "peer.clj" 338]
  [datomic.peer.Connection transact "peer.clj" 331]
  [datomic.api$transact invokeStatic "api.clj" 94]
  [datomic.api$transact invoke "api.clj" 92]
  [orcpub.routes$update_character invokeStatic "routes.clj" 673]
  [orcpub.routes$update_character invoke "routes.clj" 641]
  [orcpub.routes$do
clojure.lang.ExceptionInfo: Interceptor Exception: java.lang.IllegalArgumentException: :db.error/not-transaction-data Transaction data element must be a List or Map, got  {:execution-id 3278, :stage :enter, :interceptor :orcpub.routes/save-character, :exception-type :java.util.concurrent.ExecutionException, :exception #error {
 :cause ":db.error/not-transaction-data Transaction data element must be a List or Map, got "
 :data {:db/error :db.error/not-transaction-data}
 :via
 [{:type java.util.concurrent.ExecutionException
   :message "java.lang.IllegalArgumentException: :db.error/not-transaction-data Transaction data element must be a List or Map, got "
   :at [datomic.promise$throw_executionexception_if_throwable invokeStatic "promise.clj" 10]}
  {:type datomic.impl.Exceptions$IllegalArgumentExceptionInfo
   :message ":db.error/not-transaction-data Transaction data element must be a List or Map, got "
   :data {:db/error :db.error/not-transaction-data}
   :at [datomic.error$arg invokeStatic "error.clj" 57]_save_character invokeStatic "routes.clj" 708]
  [orcpub.routes$do_save_character invoke "routes.clj" 699]
  [orcpub.routes$save_character invokeStatic "routes.clj" 713]
  [orcpub.routes$save_character invoke "routes.clj" 712]
  [io.pedestal.interceptor$eval20469$fn__20470$fn__20471 invoke "interceptor.clj" 41]
  [io.pedestal.interceptor.chain$try_f invokeStatic "chain.clj" 52]
  [io.pedestal.interceptor.chain$try_f invoke "chain.clj" 42]
  [io.pedestal.interceptor.chain$process_all_with_binding invokeStatic "chain.clj" 152]
  [io.pedestal.interceptor.chain$process_all_with_binding invoke "chain.clj" 129]
  [io.pedestal.interceptor.chain$process_all$fn__21009 invoke "chain.clj" 165]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1973]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1973]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [io.pede}]
 :trace
 [[datomic.error$arg invokeStatic "error.clj" 57]
  [datomic.error$arg invoke "error.clj" 52]
  [datomic.error$arg invokeStatic "error.clj" 55]
  [datomic.error$arg invoke "error.clj" 52]
  [datomic.transaction$inject_all$fn__4990 invoke "transaction.clj" 128]
  [clojure.core.protocols$fn__8144 invokeStatic "protocols.clj" 168]
  [clojure.core.protocols$fn__8144 invoke "protocols.clj" 124]
  [clojure.core.protocols$fn__8099$G__8094__8108 invoke "protocols.clj" 19]
  [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
  [clojure.core.protocols$fn__8129 invokeStatic "protocols.clj" 75]
  [clojure.core.protocols$fn__8129 invoke "protocols.clj" 75]
  [clojure.core.protocols$fn__8073$G__8068__8086 invoke "protocols.clj" 13]
  [clojure.core$reduce invokeStatic "core.clj" 6828]
  [clojure.core$reduce invoke "core.clj" 6810]
  [datomic.transaction$inject_all invokeStatic "transaction.clj" 123]
  [datomic.transaction$inject_all invoke "transaction.clj" 121]
  [datomic.peer.Connection transacstal.interceptor.chain$process_all invokeStatic "chain.clj" 163]
  [io.pedestal.interceptor.chain$process_all invoke "chain.clj" 159]
  [io.pedestal.interceptor.chain$enter_all invokeStatic "chain.clj" 212]
  [io.pedestal.interceptor.chain$enter_all invoke "chain.clj" 206]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 356]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 329]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 366]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 329]
  [io.pedestal.http.impl.servlet_interceptor$interceptor_service_fn$fn__24898 invoke "servlet_interceptor.clj" 350]
  [io.pedestal.http.servlet.FnServlet service "servlet.clj" 28]
  [org.eclipse.jetty.servlet.ServletHolder handle "ServletHolder.java" 845]
  [org.eclipse.jetty.servlet.ServletHandler doHandle "ServletHandler.java" 583]
  [org.eclipse.jetty.server.handler.ScopedHandler handle "ScopedHandler.java" 143]
  [org.eclipse.jetty.server.handler.gzip.GzipHandler handletAsync "peer.clj" 338]
  [datomic.peer.Connection transact "peer.clj" 331]
  [datomic.api$transact invokeStatic "api.clj" 94]
  [datomic.api$transact invoke "api.clj" 92]
  [orcpub.routes$update_character invokeStatic "routes.clj" 673]
  [orcpub.routes$update_character invoke "routes.clj" 641]
  [orcpub.routes$do_save_character invokeStatic "routes.clj" 708]
  [orcpub.routes$do_save_character invoke "routes.clj" 699]
  [orcpub.routes$save_character invokeStatic "routes.clj" 713]
  [orcpub.routes$save_character invoke "routes.clj" 712]
  [io.pedestal.interceptor$eval20469$fn__20470$fn__20471 invoke "interceptor.clj" 41]
  [io.pedestal.interceptor.chain$try_f invokeStatic "chain.clj" 52]
  [io.pedestal.interceptor.chain$try_f invoke "chain.clj" 42]
  [io.pedestal.interceptor.chain$process_all_with_binding invokeStatic "chain.clj" 152]
  [io.pedestal.interceptor.chain$process_all_with_binding invoke "chain.clj" 129]
  [io.pedestal.interceptor.chain$process_all$fn__21009 invoke "chain.clj" 165]
  [clojure.lang.AF "GzipHandler.java" 399]
  [org.eclipse.jetty.server.handler.ContextHandler doHandle "ContextHandler.java" 1162]
  [org.eclipse.jetty.servlet.ServletHandler doScope "ServletHandler.java" 511]
  [org.eclipse.jetty.server.handler.ContextHandler doScope "ContextHandler.java" 1092]
  [org.eclipse.jetty.server.handler.ScopedHandler handle "ScopedHandler.java" 141]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 134]
  [org.eclipse.jetty.server.Server handle "Server.java" 518]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 308]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 244]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 273]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 95]
  [org.eclipse.jetty.io.SelectChannelEndPoint$2 run "SelectChannelEndPoint.java" 93]
  [org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume produceAndRun "ExecuteProduceConsume.java" 246]
n applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1973]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1973]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [io.pedestal.interceptor.chain$process_all invokeStatic "chain.clj" 163]
  [io.pedestal.interceptor.chain$process_all invoke "chain.clj" 159]
  [io.pedestal.interceptor.chain$enter_all invokeStatic "chain.clj" 212]
  [io.pedestal.interceptor.chain$enter_all invoke "chain.clj" 206]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 356]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 329]
  [io.pedestal.interceptor.chain$execute invokeStatic "chain.clj" 366]
  [io.pedestal.interceptor.chain$execute invoke "chain.clj" 329]
  [io.pedestal.http.impl.servlet_interceptor$interceptor_service_fn$fn__24898 invoke "servlet_interceptor.clj" 350]
  [io.pedestal.http.servlet.FnServlet service "s  [org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume run "ExecuteProduceConsume.java" 156]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 654]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$3 run "QueuedThreadPool.java" 572]
  [java.lang.Thread run "Thread.java" 748]]}
ervlet.clj" 28]
  [org.eclipse.jetty.servlet.ServletHolder handle "ServletHolder.java" 845]
  [org.eclipse.jetty.servlet.ServletHandler doHandle "ServletHandler.java" 583]
  [org.eclipse.jetty.server.handler.ScopedHandler handle "ScopedHandler.java" 143]
  [org.eclipse.jetty.server.handler.gzip.GzipHandler handle "GzipHandler.java" 399]
  [org.eclipse.jetty.server.handler.ContextHandler doHandle "ContextHandler.java" 1162]
  [org.eclipse.jetty.servlet.ServletHandler doScope "ServletHandler.java" 511]
  [org.eclipse.jetty.server.handler.ContextHandler doScope "ContextHandler.java" 1092]
  [org.eclipse.jetty.server.handler.ScopedHandler handle "ScopedHandler.java" 141]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 134]
  [org.eclipse.jetty.server.Server handle "Server.java" 518]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 308]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 244]
  [org.eclipse.jetty.io.AbstractConnection$ReadCallback succeeded "AbstractConnection.java" 273]
  [org.eclipse.jetty.io.FillInterest fillable "FillInterest.java" 95]
  [org.eclipse.jetty.io.SelectChannelEndPoint$2 run "SelectChannelEndPoint.java" 93]
  [org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume produceAndRun "ExecuteProduceConsume.java" 246]
  [org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume run "ExecuteProduceConsume.java" 156]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 654]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$3 run "QueuedThreadPool.java" 572]
  [java.lang.Thread run "Thread.java" 748]]}}
        at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:33)
        at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32)
        at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:55)
        at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:42)
        at io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic(chain.clj:152)
        at io.pedestal.interceptor.chain$process_all_with_binding.invoke(chain.clj:129)
        at io.pedestal.interceptor.chain$process_all$fn__21009.invoke(chain.clj:165)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at io.pedestal.interceptor.chain$process_all.invokeStatic(chain.clj:163)
        at io.pedestal.interceptor.chain$process_all.invoke(chain.clj:159)
        at io.pedestal.interceptor.chain$enter_all.invokeStatic(chain.clj:212)
        at io.pedestal.interceptor.chain$enter_all.invoke(chain.clj:206)
        at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:356)
        at io.pedestal.interceptor.chain$execute.invoke(chain.clj:329)
        at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:366)
        at io.pedestal.interceptor.chain$execute.invoke(chain.clj:329)
        at io.pedestal.http.impl.servlet_interceptor$interceptor_service_fn$fn__24898.invoke(servlet_interceptor.clj:350)
        at io.pedestal.http.servlet.FnServlet.service(servlet.clj:28)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:399)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1162)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:518)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: :db.error/not-transaction-data Transaction data element must be a List or Map, got
        at datomic.promise$throw_executionexception_if_throwable.invokeStatic(promise.clj:10)
        at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:6)
        at datomic.promise$settable_future$reify__4751.deref(promise.clj:54)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at orcpub.routes$update_character.invokeStatic(routes.clj:662)
        at orcpub.routes$update_character.invoke(routes.clj:641)
        at orcpub.routes$do_save_character.invokeStatic(routes.clj:708)
        at orcpub.routes$do_save_character.invoke(routes.clj:699)
        at orcpub.routes$save_character.invokeStatic(routes.clj:713)
        at orcpub.routes$save_character.invoke(routes.clj:712)
        at io.pedestal.interceptor$eval20469$fn__20470$fn__20471.invoke(interceptor.clj:41)
        at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:52)
        ... 40 more
Caused by: java.lang.IllegalArgumentException: :db.error/not-transaction-data Transaction data element must be a List or Map, got
        at datomic.error$arg.invokeStatic(error.clj:57)
        at datomic.error$arg.invoke(error.clj:52)
        at datomic.error$arg.invokeStatic(error.clj:55)
        at datomic.error$arg.invoke(error.clj:52)
        at datomic.transaction$inject_all$fn__4990.invoke(transaction.clj:128)
        at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8129.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8129.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at datomic.transaction$inject_all.invokeStatic(transaction.clj:123)
        at datomic.transaction$inject_all.invoke(transaction.clj:121)
        at datomic.peer.Connection.transactAsync(peer.clj:338)
        at datomic.peer.Connection.transact(peer.clj:331)
        at datomic.api$transact.invokeStatic(api.clj:94)
        at datomic.api$transact.invoke(api.clj:92)
        at orcpub.routes$update_character.invokeStatic(routes.clj:673)
        ... 47 more
[qtp827598152-346] INFO io.pedestal.http - {:msg "GET /image/spiral.gif", :line 78}
[qtp827598152-346] INFO io.pedestal.http.cors - {:msg "cors request processing", :origin "", :allowed true, :line 84}
[qtp827598152-346] INFO io.pedestal.http.cors - {:msg "cors response processing", :cors-headers {"Access-Control-Allow-Origin" "", "Access-Control-Allow-Credentials" "true", "Access-Control-Expose-Headers" "Content-Length, Last-Modified, Content-Type"}, :line 111}
```
