### ISSUE TITLE
Rogue "Burglar's Pack" missing

### ISSUE THREAD

**Issue by sehrgut** [Orcpub/orcpub#95]
When creating a character with the Rogue class, the special "Burglar's Pack" is not available in Starting Equipment. However, there is an empty item not present in the equipment picker for other classes. Attempting to save a character with this empty item selected fails with the following client-side stacktrace:

```
"Error: Invalid keyword: .
    at new Kj (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:1011:26)
    at Lj (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:1012:271)
    at Q6a (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4059:496)
    at C6 (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4059:529)
    at S6a (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4060:243)
    at B7a (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4080:270)
    at I6 (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4074:407)
    at w7a (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4075:178)
    at I6 (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4074:407)
    at w7a (https://www.dungeonmastersvault.com/js/compiled/orcpub.js:4075:178)"
```

**Comment by sehrgut** [comment]
Additional details: when refreshing the page, the following errors show up in the console and the entire character in progress is cleared:

```
"E" #error {:message "Invalid keyword: .", :data {:type :reader-exception, :ex-kind :reader-error}}
orcpub.js:4414 UNREADABLE ITEM FOUND, REMOVING.. character {:orcpub.entity.strict/selections [{:orcpub.entity.strict/key :ability-scores, :orcpub.entity.strict/option {:orcpub.entity.strict/key :standard-scores, :orcpub.entity.strict/map-value {:orcpub.dnd.e5.character/str 15, :orcpub.dnd.e5.character/dex 14, :orcpub.dnd.e5.character/con 13, :orcpub.dnd.e5.character/int 12, :orcpub.dnd.e5.character/wis 10, :orcpub.dnd.e5.character/cha 8}}} {:orcpub.entity.strict/key :class, :orcpub.entity.strict/options [{:orcpub.entity.strict/key :rogue, :orcpub.entity.strict/selections [{:orcpub.entity.strict/key :levels, :orcpub.entity.strict/options [{:orcpub.entity.strict/key :level-1}]} {:orcpub.entity.strict/key :starting-equipment-equipment-pack, :orcpub.entity.strict/option {:orcpub.entity.strict/key :}}]}]} {:orcpub.entity.strict/key :weapons, :orcpub.entity.strict/options [{:orcpub.entity.strict/key :dagger, :orcpub.entity.strict/map-value {:orcpub.dnd.e5.character.equipment/quantity 2, :orcpub.dnd.e5.character.equipment/equipped? true, :orcpub.dnd.e5.character.equipment/class-starting-equipment? true}}]} {:orcpub.entity.strict/key :armor, :orcpub.entity.strict/options [{:orcpub.entity.strict/key :leather, :orcpub.entity.strict/map-value {:orcpub.dnd.e5.character.equipment/quantity 1, :orcpub.dnd.e5.character.equipment/equipped? true, :orcpub.dnd.e5.character.equipment/class-starting-equipment? true}}]} {:orcpub.entity.strict/key :equipment, :orcpub.entity.strict/options [{:orcpub.entity.strict/key :thieves-tools, :orcpub.entity.strict/map-value {:orcpub.dnd.e5.character.equipment/quantity 1, :orcpub.dnd.e5.character.equipment/equipped? true, :orcpub.dnd.e5.character.equipment/class-starting-equipment? true}}]}], :changed true}
(anonymous) @ orcpub.js:4414
(anonymous) @ orcpub.js:4414
(anonymous) @ orcpub.js:756
Xg.l @ orcpub.js:756
(anonymous) @ orcpub.js:2904
m0a @ orcpub.js:2890
q0a @ orcpub.js:2894
E3 @ orcpub.js:2899
(anonymous) @ orcpub.js:5453
(anonymous) @ orcpub.js:5514
```

**Comment by DivertedCircle** [comment]
Suspect this is linked to #72

**Comment by sehrgut** [comment]
I believe you're right. The internal name "burglers-pack" is derived from the human-readable "Burgler's Pack" by [name-to-kw-aux](https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/common.cljc#L8). This means the rogue class definition now refers to an object `burglers-pack` that never gets defined.

Honestly, without adding some sort of aliasing to `add-keys-xform`, I don't think it's possible to rename items while keeping them valid with old characters, which #72 was trying to do.

**Comment by datdamnzotz** [comment]
@sehrgut can you kick out an alias? or should we just chalk it up to a bug, fix the internal name to match? And if people run into it, just delete and add another burglar's pack?
I can fix MY backend, but I can't fix the db's on ppls docker images.

**Comment by sehrgut** [comment]
@johnliss It's been years since I wrote any clojure, so I couldn't do it quickly and trust my implementation.

What if you kept a copy of the old "Burgler's Pack" which wouldn't be referenced from anywhere, so characters in people's DBs would match, but changed the Rogue definition to offer `burglars-pack` in its selections. From my (limited) understanding of the selection code, that seems like it would work; and let formal general-purpose aliasing be a future thing.
